import { fetchCachedReport } from "@/app/actions/analyze";
import ReportClient from "./ReportClient";

interface PageProps {
  params: Promise<{ handle: string }>;
}

export default async function ReportPage({ params }: PageProps) {
  const { handle } = await params;

  // Try to fetch cached report from KV
  const cached = await fetchCachedReport(handle);

  return (
    <ReportClient
      handle={handle}
      cachedReport={cached.found ? cached.report : undefined}
      cachedAnalysisType={cached.found ? cached.analysisType : undefined}
      cachedCompetitorHandle={cached.found ? cached.competitorHandle : undefined}
      cachedCreatedAt={cached.found ? cached.createdAt : undefined}
    />
  );
}

// Generate metadata for the page
export async function generateMetadata({ params }: PageProps) {
  const { handle } = await params;
  return {
    title: `@${handle} - X Growth Analysis | GrokXBoost`,
    description: `AI-powered growth analysis for @${handle} on X, generated by Grok.`,
  };
}
